apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: demo
description: My application CI/CD pipeline
serialPipeline:
  stages:
  - targetId: dev
    profiles: []
  - targetId: staging # <<-- New stage for staging
    profiles: []
    # Add this block to require a manual approval
    strategy:
      standard:
        postdeploy:
          actions: []
        predeploy:
          actions: []

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: development cluster
gke:
  cluster: projects/divijesh-project/locations/asia-south1/clusters/dev-cluster

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
requireApproval: true
description: staging cluster
gke:
  cluster: projects/divijesh-project/locations/asia-south1/clusters/staging-cluster
