steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/divijesh-project/pipeline/app1-image:latest', './app1' ]
  id: 'Build Docker Image for App1'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/divijesh-project/pipeline/app1-image:latest' ]
  id: 'Push Docker Image for App1'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/divijesh-project/pipeline/app2-image:latest', './app2' ]
  id: 'Build Docker Image for App2'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/divijesh-project/pipeline/app2-image:latest' ]
  id: 'Push Docker Image for App2'
