apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: demo
description: My application CI/CD pipeline
serialPipeline:
  stages:
  - targetId: test
    profiles: []
<<<<<<< HEAD
  - targetId: staging # <<-- New stage for staging
=======
  - targetId: staging 
>>>>>>> 866610df9cedfaea65ab442fdbd990491607b80c
    profiles: []
    # Canary deploy
    strategy:
      canary:
        runtimeConfig:
          kubernetes:
            serviceNetworking:
              service: "my-service"
              deployment: "my-deployment"
        canaryDeployment:
          percentages: [50]
          verify: false
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: test
description: development cluster
gke:
  cluster: projects/divijesh-project/locations/asia-south1/clusters/test-cluster

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: staging
requireApproval: true
description: staging cluster
gke:
  cluster: projects/divijesh-project/locations/asia-south1/clusters/staging-cluster
