apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: demo
description: My application CI/CD pipeline
serialPipeline:
  stages:
  - targetId: dev
    profiles: []

---

apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
description: development cluster
gke:
  cluster: projects/divijesh-project/locations/asia-south1/clusters/cluster

