steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/divijesh-project/pipeline/app1-image:latest', './app1' ]
  id: 'Build Docker Image for App1'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/divijesh-project/pipeline/app1-image:latest' ]
  id: 'Push Docker Image for App1'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'asia-south1-docker.pkg.dev/divijesh-project/pipeline/app2-image:latest', './app2' ]
  id: 'Build Docker Image for App2'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'asia-south1-docker.pkg.dev/divijesh-project/pipeline/app2-image:latest' ]
  id: 'Push Docker Image for App2'

- name: 'google/cloud-sdk:latest'
  entrypoint: 'sh'
  args:
  - -xe
  - -c
  - |
    gcloud components update # (Recommended to keep)
    gcloud deploy apply --file deploy/pipeline.yaml --region=asia-south1
    gcloud deploy apply --file deploy/dev.yaml --region=asia-south1
    sleep 10 # Add this line
    gcloud deploy releases create 'app-release-${SHORT_SHA}' --delivery-pipeline=gke-cicd-pipeline --region=asia-south1 --skaffold-file=skaffold.yaml


options:
  logging: CLOUD_LOGGING_ONLY
